[
    "-[temp] The Little Christmas Overhaul",
    "-[temp] [NINI] Bless EC 0004 Slutty",
    "+Demoniac_Texture (for CustomBreton) v",
    "+DS Weapon Pack by Team TAL",
    "+Bless Leoni Armor (UUNP) (TMB)",
    "+Bless Leoni Armor (CBBE)",
    "+BDO Valkyrie Venslar Retouched (UUNP) (TMB)",
    "+BDO Valkyrie Venslar Retouched (UNPB)",
    "+BDO Kylia Cuiress (UUNP) (TMB)",
    "+[Ninirim Pirated Mods] [NINI] Shining Will - Damaged (UUNP) (TMB)",
    "+[Ninirim Pirated Mods] [NINI] Charles Rene - Slutty (UUNP) (TMB)",
    "+[Ninirim Pirated Mods] [NINI] Bless 0001 - Slutty (UUNP) (TMB)",
    "+[NINI] Red Nose Slutty (UUNP) (TMB)",
    "+[NINI] Kokoro (UUNP) (TMB)",
    "+[Ninirim Pirated Mods] [NINI] BDO Kokoro (CBBE BS)",
    "+[NINI] Fire Keeper - Damaged (UUNP) (TMB)",
    "+[NINI] Dawley Syande (UUNP) (TMB)",
    "+[NINI] Dawley Syande Full HDT",
    "+[NINI] Bless RB 3004 Damaged (UUNP) (TMB)",
    "+[NINI] Bless MD 0004 - Damaged (UUNP) (TMB)",
    "+[NINI] Bless HV 0102 Slutty (UUNP) (TMB)",
    "+[BDO Pirated Mods] Ranger's Kyrill Armor (UUNP) (TMB)",
    "+[BDO Pirated Mods] BDO Ranger Sitaila (UUNP) (TMB)",
    "+[BDO Pirated Mods] BDO Ranger Sitaila",
    "+[BDO Pirated Mods] BDO Ranger NewCloth (UUNP) (TMB)",
    "+[BDO Pirated Mods] BDO Ranger NewCloth",
    "+[Dint] BDO SinTerna (Dark Knight) v1.3 Retouched",
    "+[BDO Pirated Mods] BDO Dark Knight v1.4 (UUNP) (TMB)",
    "+[BDO Pirated Mods] [Dint] Dark Knight v1.5 + HDT Weapons (female)",
    "+Victorian Dress (UUNP) (TMB)",
    "+DEM Victorian",
    "+Royal Hunting (UUNP) (TMB)",
    "+Royal Hunting",
    "+Karter's Summer Dresses (UUNP) (TMB)",
    "+Karter's Summer Dresses",
    "+Epoch Weapon Pack",
    "+Bless Armor Pack by Team TAL",
    "+BDO Ahon Kirus (UUNP) (TMB)",
    "+BDO Venslar (UUNP) (TMB)",
    "+BDO Shudad Cuirass (UUNP) (TMB)",
    "+BDO Hilat (UUNP) (TMB)",
    "+BDO Pack II v1.0 by team TAL",
    "+BDO Tyrie Armor (UUNP) (TMB)",
    "+BDO Valkyrie Armor (UUNP) (TMB)",
    "+BDO Ignis Dress (UUNP) (TMB)",
    "+BDO Crowned Eagle (UUNP) (TMB)",
    "+[BDO Pirated Mods] BDO Pack 2 by team TAL",
    "+[BDO Pirated Mods] BDO Pack 1 by team TAL",
    "+More Draconic Dragon Aspect - Custom Colors - for Miraak Unique Dragon Aspect by the-ebonarm",
    "+More Draconic Dragon Aspect - Custom Colors",
    "+Miraak Unique Dragon Aspect by the-ebonarm",
    "+Followers Can Read Dragon Language",
    "-[NINI] Hair Pack",
    "-Weathers - Merged (Vivid Weathers version)",
    "+Weathers - Merged (NLA version)",
    "-Natural Lighting and Atmospherics for ENB (for Snapdragon ENB)",
    "+Ella’s Fantasy Eyes",
    "+Freckle Mania 2",
    "+Creepier Daedric Princes",
    "+FreeFlyCam - SKSE",
    "+Vivid Weathers (for Goddess ENB)",
    "-FAMOUS - Fitness And Muscle Options Utility Suite for UNP and 7B",
    "-Tumblr Gift 1 – Halo’s Overlays",
    "+Karter’s Herbalist Dress + Dark Luxury Mashup (TMB)",
    "+Horse Camera Bug Fix",
    "+ConsoleUtil",
    "+Better lighting for Face Light and Facelight Plus",
    "+NiOverride Pose Adjustments [pose]",
    "+HDT Breast And Butt Physics - TBBP BBP Supported",
    "-FNIS - Output - OSA_OSEX 2.02 Beta",
    "-OSA_OSEX 2.02 Beta",
    "+CITRUS Heads (HD Meshes)",
    "-Miraak Follower - Naked comments",
    "-3ds Max - working",
    "-Truly Light Glass Armor (female) - Standalone",
    "+Apachii Divine Elegance Store - retextured",
    "-Hearth Craft",
    "-[x] Immersive Dragon Sounds -iDS-",
    "+Meshes cleaned by Nif Healer",
    "+Arya - Play data",
    "-[99] ----------UNSORTED----------",
    "-temp",
    "-CCO Resource File",
    "-[99] ----------DO NOT ACTIVATE----------",
    "+Bashed Patch",
    "+Mega Patch",
    "+DynDOLOD - Output - High",
    "+[98] ----------MERGED & BASHED & PATCHES----------",
    "-[x] JKs Skyrim LITE and Dawn Of Skyrim Directors Cut Patch",
    "+Deadly Dragons Script Patch",
    "-Immersive Amazing Follower Tweaks - Interesting NPCs Patch",
    "+Imperious - TF - Patch",
    "+More Patches for CACO - Konahriks Accoutrements",
    "+More Patches for CACO - Interesting NPCs",
    "+More Patches for CACO - Cutting Room Floor",
    "+Clothing and Clutter Fixes - RS Children - Compability Patch",
    "+Complete Crafting Overhaul Remade - CCO Compatibility Patch for WAF True Weapons",
    "+Complete Crafting Overhaul Remade - CCO Compatibility Patch for Skyrim Immersive Creatures",
    "+The Paarthurnax Ultimatum - FuzRoDoh Compatibility Patch",
    "-Improved Closefaced Helmets - Falskaar",
    "-[x] Ordinator - WAFR and CCOR patch",
    "+Unique Uniques - Weapons and Armor Fixes Remade Patched Replacer ESP",
    "+Transparent and refracting Glass Eqmnt - aMidianBorn Glass Eqmnt with Refraction Patch",
    "-Thunderchild - Epic Shouts and Immersion - Wyrmstooth Patch",
    "+Skyrim Realistic Texture Overhaul dragons 4-8K - Deadly Dragons & Wyrmstooth Retextures",
    "+RS Children - Interesting NPCs Patch",
    "-RS Children - Wyrmstooth Patch",
    "-RS Children - Falskaar Patch",
    "+Realistic HD Woodcutter's Axe - Campfire Patch",
    "+RaceCompatibility - Dialog Changes - Interesting NPCs Patch",
    "+RaceCompatibility - Dialog Changes - Inigo Patch",
    "+RaceCompatibility - Dialog Changes - Guard Dialogue Overhaul Patch",
    "-RaceCompatibility - Dialog Changes - Falskaar Patch",
    "-RaceCompatibility - Dialog Changes - Alternate Start Patch",
    "-Empty Weather and Lighting - Merged.esp",
    "-OBIS - Organized Bandits In Skyrim - Alternate Start + Dawnguard Patch",
    "+Snazzy HD Noble Beds - Cutting Room Floor - Patch",
    "+Lanterns of Skyrim - All in One - Dawnguard Patch",
    "+Improved Closefaced Helmets - Patches",
    "+Animallica + One With Nature patch",
    "+Skyrim Immersive Creatures + One With Nature patch",
    "+Cutting Room Floor - RS Children Patch",
    "+CACO - LL Potion Replacer - Compatibility patch for potions not included in LL file",
    "+CACO - LL Potion Replacer - Compatibility Patch",
    "+Mortal Enemies - De-aimbot Your Foes - SIC Patch",
    "+Extra CACO Compatibility Patches - CACO + Art of the Catch Patch",
    "+Complete Alchemy and Cooking Overhaul - Patches (inc. Wyrmstooth)",
    "+Clothing and Clutter Fixes - Interesting NPCs - Compability Patch",
    "+Apocalypse - Magic of Skyrim - Ordinator Compatibility Patch",
    "+Beasts of Tamriel - One with Nature patch",
    "+Animal Tweaks - Skyrim Immersive Creatures Patch",
    "+Animal Tweaks - OBIS Patch",
    "+Animal Tweaks - One With Nature Patch",
    "+[97] ----------COMPATIBILITY PATCHES----------",
    "+General - Merged",
    "+Skyrim Unbound (Alternate Start)",
    "-Alternate Start - Live Another Life",
    "+General - Patch",
    "+tf_mods",
    "+[96] ----------LOAD LATE----------",
    "-[!] Enhanced ENB Night Eye",
    "+Bug fixes",
    "+Run For Your Lives",
    "+When Vampires Attack",
    "+Wiseman303's Flora Fixes",
    "+Vanilla Mannequin Script Fix",
    "-Fix Slow Time Camera",
    "+Enchantment Reload Fix",
    "+RaceCompatibility - Dialog Changes",
    "+[95] ----------BUG FIXES PART 2----------",
    "+Uninterrupted Invisibility",
    "+Uninterrupted Ethereal Form",
    "+Infinite Weapon Charges",
    "+Skills Config",
    "+Faster Mining",
    "+[25] ----------CHEATS----------",
    "+[24] ----------ENB DATA FILES----------",
    "-FNIS - Output - Without [pose] mods but with JRDance",
    "-FNIS - Output - Without [pose] mods but with Dance Together",
    "-FNIS - Output - Without [pose] mods",
    "+FNIS - Output - With [pose] mods",
    "+FNIS - Don't ask again for link",
    "+Poser Hotkeys",
    "+Poses - Merged",
    "+[23c] ----------ANIMATIONS - FNIS OUTPUT & MERGED----------",
    "+My FNIS Spells",
    "+Magiska",
    "-Play Random Idle",
    "+Realistic Animation Project - Idles",
    "+Realistic Animation Project - Movement",
    "+Immersive Animations",
    "+XP32 New Animation Package - Nexus Exclusive",
    "-Proper Torch Wield - Hold Your Torch Away From Your Face",
    "+Pretty Sit Idle v1.41c",
    "-Lifelike Idle Animations",
    "-Pretty Female Idles",
    "+New Animation - Power Thrust",
    "-Male Idle Animation Replacer",
    "+Hush Doggy",
    "+Hold Your Torch Higher",
    "+Dragon Animation Replace",
    "+Blocking Animation Pack",
    "+althea-alt Pose Resources 1-3 + 6",
    "+[23b] ----------ANIMATIONS - WITHOUT ESP----------",
    "-JRDance",
    "-Dance Together - English translation",
    "-Dance Together (Chinese)",
    "+TKDodge fixes by aareyn",
    "+TK Dodge",
    "+Fores New Idles in Skyrim - FNIS - Add-On for Spells",
    "+Poser Module for OSA",
    "+Public Poser [pose]",
    "-[x] Additional Dramatic Poses for Pinup Poser",
    "+MK Poser [pose]",
    "+Honey Pose [pose]",
    "+YuiHsPOSE Mod [pose]",
    "-[x] FNIS Ero Idle",
    "+Shocky's PosePack Humans [pose]",
    "+Pretty Motion Collection [pose]",
    "+Wulf's Poser [pose]",
    "+Aloe Poses [pose]",
    "+FuwaPose [pose]",
    "+Arsenic Pose [pose]",
    "+MergaPose [pose]",
    "+Kinoko Pose [pose]",
    "+GomaPero Poses [pose]",
    "+Halo's Poser S [pose]",
    "+Horses Revamped - Animations",
    "+Animated Dragon Wings",
    "+Facial Expressions Project",
    "+[23a] ----------ANIMATIONS - WITH ESP----------",
    "+[23] ----------ANIMATIONS----------",
    "+OSex 1.09 BETA",
    "-Spouses Enhanced",
    "-SexLab MatchMaker",
    "-[22] ----------ADULT----------",
    "+Immersion - Merged",
    "+Immersion - Patch",
    "+[21b] ----------IMMERSION - MERGED----------",
    "-Relationship Dialogue Overhaul - RDO",
    "+Ciri voice addon for PC Headtracking and Voice Pack",
    "+PC Head Tracking and Voice Type",
    "+Lore-Based Loading Screens",
    "+No More Glowing Edges Mod",
    "+No Enchant Shaders or Sounds",
    "+Wet and Cold",
    "+Skyrim Coin Replacer Redux",
    "-[x] Player Headtracking",
    "+OBIS - Organized Bandits In Skyrim",
    "+Lanterns of Skyrim - All In One",
    "+DIVERSE SKYRIM",
    "+Immersive Patrols",
    "+Hearthfire Multiple Adoptions",
    "+Holidays",
    "+Female Mannequins",
    "+Tentapalooza for Campfire",
    "-[x] Dig Site -- Relic Hunter Tents for Campfire",
    "+Carriage and Ferry Travel Overhaul (Formerly Complete Fast Travel Overhaul)",
    "+Campfire - Complete Camping System",
    "+Bring Out Your Dead",
    "+Art of the Catch",
    "+[21a] ----------IMMERSION - GENERAL----------",
    "+[21] ----------IMMERSION----------",
    "+Audio - Merged",
    "+Audio - Manual Patches",
    "+[20f] ----------AUDIO - MERGED----------",
    "+Smooth Blades Draw and Sheath (with audio dynamic sneak)",
    "+Skeletons don't breathe",
    "+Realistic Husky Sounds",
    "+Noisy Fox Fix",
    "+Nirnroots - Silenced",
    "+Heart of the Beast - Werewolf Sound and Texture Overhaul",
    "+FSS - Better Bards",
    "+Female Bard Cover by Malukah Ingame",
    "+Enhanced Draugr FX",
    "-Brave Female Voice Replacer",
    "+Better Horse Pain Sounds",
    "+[20e] ----------AUDIO - OTHER----------",
    "+Ultra Realistic Crossbow Shoot Sounds",
    "+Ultra Realistic Bow Shoot Sounds",
    "+OMINOUS Dragon Soul Absorb Music",
    "+[20d] ----------AUDIO - COMBAT & MAGIC----------",
    "+Audio Overhaul for Skyrim 2",
    "+[20c] ----------AUDIO - OVERHAUL----------",
    "+Music - Smashed Patch",
    "+Symphonies Of Skyrim",
    "+Celtic Music in Skyrim (Main + Combat + Dungeons)",
    "+Musical Lore (Soundtrack Mod By Nir Shor)",
    "+Immersive Music by Hothtrooper44",
    "+Additional Music Project",
    "+Fantasy Soundtrack Project",
    "-[20b] ----------AUDIO - MUSIC - IN GAME----------",
    "-Enocguitar Skyrim main theme replace",
    "-Skyrim Theme Menu Music --- Violin Cover by Jason Yang",
    "-Main Menu Music Replacer - The Dragonborn Comes",
    "-Main Menu Music Replacer - Tale of the Tongues",
    "-Main Menu Music Replacer - Reignite",
    "-Main Menu Music Replacer - Lead Them or Fall",
    "-Main Menu Music Replacer - - Two Steps from Hell - Freedom Fighters",
    "+Main Menu Music Replacer - - Courage of Ordinary Mortals",
    "-Main Menu Music Replacer - Beauty of Dawn",
    "+[20a] ----------AUDIO - MUSIC - MAIN MENU----------",
    "+[20] ----------AUDIO----------",
    "+[19b] ----------WEATHER, LIGHTING & ATMOSPHERICS - MERGED----------",
    "+Enhanced Lights and FX",
    "-Relighting Skyrim Series",
    "-ELE - Lite - Interiors Only",
    "+[18a] ----------WEATHER, LIGHTING & ATMOSPHERICS - LIGHTING----------",
    "-Natural Lighting Vivid Atmospherics - Empty ESP to trick game",
    "-Natural Lighting Vivid Atmospherics",
    "-[x] True Storms - Thunder and Rain Redone",
    "-Vivid Weathers (.esp hidden)",
    "+[19a] ----------WEATHER, LIGHTING & ATMOSPHERICS - WEATHER----------",
    "+[19] ----------WEATHER, LIGHTING & ATMOSPHERICS----------",
    "+Gameplay - Merged",
    "+Gameplay - Patch",
    "+[18e] ----------GAMEPLAY - MERGED----------",
    "+Thunderchild - Epic Shouts and Immersion",
    "+Natures Lure - Throw Voice Shout",
    "+More Draconic Dragon Aspect",
    "+Dragonborn Shout - Ultimate Dragon Aspect Overhaul",
    "+[18d] ----------GAMEPLAY - SHOUTS----------",
    "+Witchhunter Spells and Prayers Pack",
    "+Summermyst - Enchantments of Skyrim",
    "-Wintermyst - Enchantments of Skyrim",
    "-[x] Mass effect Biotic Spells in Skyrim",
    "-[x] Dragon Age Spells",
    "+Apocalypse - Magic of Skyrim",
    "+Acquisitive Soul Gems Multithreaded",
    "+[18c] ----------GAMEPLAY - MAGIC----------",
    "+Werewolf Perks Expanded - Dawnguard",
    "+Moonlight Tales - Werewolf and Werebear Essentials",
    "+[18b] ----------GAMEPLAY - WEREWOLVES & VAMPIRES----------",
    "+Wildcat - Combat of Skyrim",
    "+Aurora - Standing Stones of Skyrim",
    "+Better Stealing",
    "+Crime Overhaul",
    "+Imperious - Races of Skyrim",
    "+Simply Knock",
    "-Combat Evolved",
    "+Mortal Enemies - De-aimbot Your Foes",
    "+VioLens - A Killmove Mod",
    "+CACO-Ordinatored",
    "+Complete Alchemy and Cooking Overhaul",
    "+Ordinator - Perks of Skyrim",
    "+Nock to Tip",
    "+Combat Drama Overhaul",
    "+Archery Gameplay Overhaul",
    "+[18a] ----------GAMEPLAY - OVERHAUL----------",
    "+[18] ----------GAMEPLAY----------",
    "+Locations and Quests - Merged",
    "+Quests & Locations - Patch",
    "+[17c] ----------QUESTS - MERGED----------",
    "+Thieves Guild Alternate Routes - Taking Care of Business Mod",
    "+Immersive Realistic Party Clothing Overhaul Enhanced",
    "+Less Tedious Thieves Guild",
    "-Civil War Overhaul",
    "-World Eater Beater",
    "+The Paarthurnax Ultimatum",
    "+Timing is Everything - Quest Delay and Timing Control",
    "+Thieves Guild Requirements - No Auto Quest Start Brynjolf",
    "+House of Horrors Alternate Ending",
    "+Dungeon Quest Awareness",
    "-[x] Blood and Silver - Cidhna Mine Expanded",
    "+All Thieves Guild Jobs Concurrently",
    "+[17b] ----------QUESTS - EXISTING----------",
    "-The Wheels of Lull",
    "+High Resolution Texture - Dragon Priest Helmets (Konahriks Accoutrements)",
    "+Konahrik's Accoutrements - Dragon Priest Armory",
    "+[17a] ----------QUESTS - NEW----------",
    "+[17] ----------QUESTS----------",
    "-Aether Suite",
    "-Pale Marsh Manor - A Unique Player Home",
    "-Sean Beautiful Valley",
    "-The Woods",
    "-The Oasis",
    "-Clearwater Grotto",
    "-Black Hole",
    "-[16c] ----------LOCATIONS - NEW - DISABLE FOR REG PLAY----------",
    "-[x] Tactical Valtheim",
    "+JKs Skaal village",
    "+JKs Cities - Lite and SuperLite",
    "+Dawn of Skyrim (Director's Cut)",
    "-Dawn of Skyrim Collection",
    "+Old Hroldan Ruins",
    "+Immersive College of Winterhold",
    "+[16b] ----------LOCATIONS - EXISTING----------",
    "-The Evil Mansion - Final Edition",
    "-[x] Island Fast Travel",
    "+Hammet's Dungeon Packs for LE",
    "-Forgotten Dungeons",
    "-Darkend",
    "-Better Falskaar and Wyrmstooth Map With Roads",
    "-Wyrmstooth",
    "-Falskaar",
    "+[16a] ----------LOCATIONS - NEW----------",
    "+[16] ----------LOCATIONS----------",
    "+Items added to player home containers",
    "+Player Homes - Merged",
    "+Player Homes - Patch",
    "+[15c] ----------PLAYER HOMES - MERGED----------",
    "+Breezehome TNF - Elianora's Flavour",
    "+[15b] ----------PLAYER HOMES - EXISTING----------",
    "+Thief's Hideout Ultimate",
    "+Raven Nest - player home in Solstheim",
    "+Tiny Shack - Painting Retexture",
    "+Tiny Shack (Lillehus)",
    "+The Rookery - Bard and Thief Loft in Solitude",
    "+The Little Keep",
    "+Sahrot Od Dein",
    "+Pinegrove Lodge - Family house",
    "+Nyyrikki",
    "+Moonwatch Manor Returns",
    "-Tirashan - Necromancer Home",
    "-Dragon Tree Temple",
    "+Deinsehun",
    "+Dawnwood Shallows",
    "+[15a] ----------PLAYER HOMES - NEW----------",
    "+[15] ----------PLAYER HOMES----------",
    "+Enhanced Vanilla TreesSkyrim Flora Overhaul Pines",
    "+Peak Aspens",
    "+Environment - Patch",
    "+[14c] ----------ENVIRONMENT - MERGED----------",
    "+RUSTIC WORD WALLS",
    "-Renthal HD Flora all in one natural colors",
    "+OH GOD BEES - More Bees--More Hives--HD Textures",
    "+WATERplants - retexture by Pfuscher",
    "+EWIs HD Treebarks Solstheim",
    "+EWIs Blackreach Mushrooms",
    "+aMidianBorn Solstheim Landscape",
    "+[14b] ----------ENVIRONMENT - MESHES & TEXTURES ONLY----------",
    "+Skyrim Flora Overhaul - SFO Billboards for v2.5b",
    "+Northfire's Photoreal Mountains LOD (SMC component)",
    "+Enhanced Landscapes - Merged",
    "+Enhanced Landscapes",
    "+DynDOLOD - Data",
    "-Skyrim High Definition LODs - Falskaar LOD Textures",
    "+Skyrim High Definition LODs - Dragonborn LOD Textures",
    "+Skyrim High Definition LODs",
    "+TES5LODGen - Vanilla Skyrim LOD Billboards",
    "+Gildergreen Regrown",
    "+[14a] ----------ENVIRONMENT - GENERAL----------",
    "+[14] ----------ENVIRONMENT----------",
    "+NPCs - Merged",
    "+NPCs - Manual Patch",
    "+[13d] ----------NPCS & FOLLOWERS - MERGED----------",
    "+Miraak - Dragonborn Follower - AI Tweaks",
    "+Vanilla Followers AI",
    "+Follower Live Package - ReTranslation",
    "+FollowerLivePackage (inc. Convenient Horses and EFF patches)",
    "+Extensible Follower Framework",
    "-[x] Immersive Amazing Follower Tweaks",
    "-Simple Follower Mount",
    "+Serana-Daughter of Coldharbor",
    "+Serana Dialogue Edit",
    "+No More Stupid Dog Comments",
    "+Move it Dammit for NPC Companions and Followers",
    "+Guard Dialogue Overhaul",
    "+Multiple Floors Sandboxing",
    "+Follower Trap Safety",
    "+[13c] ----------NPCS & FOLLOWERS - EXISTING - BEHAVIOR----------",
    "+Bijin + BVFE Serana and Family -- UUNP Special Seraphim bodies + UUNP Special texture patches",
    "+BVFE - Serana and Family (#12)",
    "-Bijin AIO (#11)",
    "+Bijin NPCs (#10)",
    "+Bijin Wives (#9)",
    "+Bijin Warmaidens (#8)",
    "+The College of Winterhold - NPC Improvement (#7)",
    "+Handsome Courier (#6)",
    "+Ultimate NPC Overhaul -DRAGONBORN- (#5)",
    "+Ultimate NPC Overhaul -DAWNGUARD- (#4)",
    "+Males of Skyrim (#3)",
    "+Inhabitants of Skyrim - NPC Overhaul (#2)",
    "+The Ultimate NPC Overhaul (#1)",
    "+RS Children Overhaul",
    "+[13b] ----------NPCS & FOLLOWERS - EXISTING - APPEARANCE----------",
    "+Populated Solstheim",
    "+Miraak - Dragonborn Follower",
    "+Interesting NPCs",
    "+INIGO",
    "+[13a] ----------NPCS & FOLLOWERS - NEW----------",
    "+[13] ----------NPCs & FOLLOWERS----------",
    "+Creatures - Merged",
    "+Creatures - Smashed Patch",
    "+[12d] ----------CREATURES - MERGED----------",
    "+NARC - No Animals Report Crimes (inc. Falskaar patch)",
    "+One With Nature - Dynamic Animals and Creatures",
    "+Convenient Horses",
    "-Immersive Horses",
    "+Dragons Shout with Voice",
    "+Dragon Priests - Enhanced",
    "+Animal Tweaks",
    "+[12c] ----------CREATURES - EXISTING - BEHAVIOR----------",
    "+Realistic Primitive Horse Breeds",
    "+The Decayed Dragon - Durnehviir Retex",
    "+Sahrotaar Retexture",
    "+Spooky Avenging Wraith for Apocalypse",
    "+2spooky4me ghosts",
    "+Scaly Serpentine Dragon HD",
    "+Supreme Alduin",
    "+True Wolves of Skyrim - Animallica Patch - 2k",
    "+True Wolves of Skyrim - SIC - 2k",
    "+True Elk Of Skyrim or TEOS - SIC Patch",
    "+True Elk Of Skyrim or TEOS - Animallica Patch",
    "+True Elk Of Skyrim or TEOS",
    "+Lepidoptera Of Skyrim",
    "+Husky HD Recolor - Bran and Sceolang Replacer",
    "+[12b] ----------CREATURES - EXISTING - APPEARANCE----------",
    "+Skyrim Immersive Creatures",
    "+Beasts of Tamriel",
    "-Sea of Spirits",
    "+Deadly Dragons",
    "+Chaos Dragons - Deadly Dragons Patch",
    "+Chaos Dragons customized - Vulthuryol only",
    "+Chaos Dragons",
    "+Diverse Dragons Collection",
    "-Blaze Of Eventide",
    "+Birds of Skyrim - Ruhadre Patch - USLEEP Compatible",
    "+Birds of Skyrim",
    "+Animallica - Skyrim Wildlife Overhaul (Customized)",
    "+[12a] ----------CREATURES - NEW----------",
    "+[12] ----------CREATURES----------",
    "-[11] ----------FREE SPACE IDK----------",
    "+Equipment02 - Merged",
    "+Equipment01 - Merged",
    "+Equipment01 - Patch",
    "+Equipment00 - Merged",
    "+Equipment00 - Patch",
    "+USLEEP WAFR CCF CCOR IJ - Smashed Patch",
    "+[10] ----------ARMOR & CLOTHING & ACCESSORIES & WEAPONS - MERGED----------",
    "+TF Unique Meshes by Race",
    "+aMidianBorn Book of Silence - Content Add-On",
    "+[09] ----------ARMOR & WEAPON COLLECTIONS----------",
    "+Long Bow Retextured",
    "+Real Bows Painted",
    "+Real Bows",
    "+Nightingale Pride - Bow and Blade Reincarnation",
    "+Elven Weapon for Silence",
    "+[08c] ----------WEAPONS - APPEARANCE----------",
    "+Noldor Content Pack - Nock to Tip compatibility patch",
    "+Nock to Tip Compatabilty Patches",
    "+Warrior Within Weapons - Nock to Tip Compatibility Patch",
    "+Torch Arrows - Nock to Tip Compatibility Patch",
    "+Lore Weapon Expansion - Nock to Tip replacer esp",
    "+Isilmeriel LOTR Weapons Collection - Nock to Tip Compatibility Patch",
    "+Grace Darklings Weaponry Packs - Nock to Tip Compatibility Patch",
    "+Ghosus Weapon Pack - Nock to Tip Compatibilty Patch",
    "+Dragon Age Series Weapon Packs - Nock to Tip Compatibility Patch",
    "+[08b] ----------WEAPONS - COMPATIBILITY PATCHES----------",
    "+Imperial Dragonknight Armory",
    "+Miraak's Dragon Era Weapons",
    "+Lost LongSwords",
    "+Lore Weapon Expansion",
    "+JaySuS Swords (assets only)",
    "+Eidolon's Edge by FavoredSoul",
    "+Farinelli's Hammerfell Armoury",
    "+Ygrayne by FavoredSoul",
    "+Warrior Within Weapons",
    "+Unique Uniques",
    "+Unique Bows Collection",
    "+Torch Arrows",
    "+The Huntsman",
    "+Sword of the Seeker by Favoredsoul",
    "+Skycutter by Favoredsoul",
    "+Nameless Light by FavoredSoul",
    "+Isilmeriel LOTR Weapons Collection",
    "+Grace Darklings Weaponry Packs",
    "+Ghosus Weapon Pack",
    "+Faction Crossbows",
    "+Drunkzealot's Somewhat Historically Accurate Weapons",
    "+Dragon Weapon Pack",
    "+Dragon Age Series Weapon Packs",
    "+[08a] ----------WEAPONS - PACKS----------",
    "+[08] ----------WEAPONS----------",
    "+Lind's outfits - retextures",
    "+UNP Armored Bikini Leather texture",
    "+Cloaks of the Nords",
    "+Hedge Mage Armor - Recolors (Custom Mix)",
    "+Brigida Dress Colour Variations - Retex",
    "+UNP Ranger Armor Retextures",
    "-Witcher 3 Ciri's DLC Outfit - Retexture",
    "+Ciri (Witcher 3) Armor HD Retexture - Black diffuse",
    "+Ciri (Witcher 3) Armor HD Retexture",
    "+Misfit Mage - Raven's Retexture",
    "+Unclaimed Delivery - Personal Retexture",
    "+Rogue Sorceress Outfit Retextured",
    "+Deadly Trio Sword Master Armor Retexture",
    "+Sotteta Necromancer Outfit - Now With Pants",
    "+Scarlet Dawn Armor - Raven's Retexture",
    "+Hotpants Bikini - Raven's Retexture",
    "+Demon Hunter Armor - Retextures",
    "+Crimson Twilight - Tetrodoxin's Purple Pattern Retex",
    "+Wedding Rings by Ezuka - Dragon Cult engagement ring replacer",
    "+Mavari Armor - Black Retexture",
    "+Glass fix for Cheskos Wearable Lanterns",
    "+Imperial Investigator Armor - Raven's Cloak Retexture",
    "+DreamBurrows Imperial Investigator Retexture",
    "+DreamBurrows Princess of The Woods Retexture",
    "+Crimson Twilight Armor - Additional Colors",
    "+SOS Male Underwear Recolor (Miraak blue)",
    "+Nightingale Prime HD",
    "+Improved Amulet of Stendarr",
    "+UUNP HDT LUX COLLECTION",
    "+RUSTIC CLOTHING",
    "+Dawn of the Dawnguard Armor",
    "+Daedric Armor Set 2k-4k Retexture",
    "+Ashland Apparel",
    "-Standalone Witcher 3 Female Armor Retextures",
    "-TDN Vampire Armor Retexture",
    "-Skaal Clothes HD Revival",
    "-HD Miraak Remake",
    "-EotW Mage Robes of Skyrim + Hearthfire DLC Robes Addon",
    "-Dragonborn Mages Robes Retexture Pack",
    "-[x] Dovahkinder Collection - Old replacer version (Vanilla + HF)",
    "+[07d] ----------ARMOR & CLOTHING & ACCESSORIES - TEXTURES & MESHES----------",
    "+[NINI] BDO Orwen Travel + retex (UUNP) (TMB)",
    "+Adventurers Mashup Compilation (UUNP) (TMB)",
    "+TMB Armored Bikini - Tweaks",
    "+TMB Armored Bikini",
    "+Witcher 3 Female Armors (TMB)",
    "+Hunting Grounds Outfit (TMB)",
    "+Warfare Armor (UNPTF)",
    "+Gilded Doublet Outfit (UUNP) (TMB)",
    "+Katarina Armor (UUNP) (TMB)",
    "+BDO Clead Cuirass Retouched (UUNP) (TMB)",
    "+BLESS Online Armors Pack (UUNP) (TMB) + retex",
    "+Light Glass Armor (UUNP) (TMB)",
    "+Linkle Outfit (UUNP) (TMB)",
    "+Bless MD0007 (UUNP) (TMB) + retex",
    "+Bless 00022 Dress (UUNP) (TMB) + retex",
    "+Ebony Valkyrie Armor (UUNP) (TMB)",
    "+Gallery of Armor (UUNP) (TMB)",
    "+SC - Witch of the Wilds (UUNP) (TMB)",
    "-The Witcher 3 Armors UUNP HDT + TMB meshes",
    "+The Book of UUNP (TMB)",
    "+Fine Imperial Dress (UUNP) (TMB)",
    "+Apachii Divine Elegance Store (TMB)",
    "+Viking Armors (UUNP) (TMB)",
    "+Ranger's Berne Armor (UUNP) (TMB)",
    "+West Wind Combat Series - Misfit Mage (UUNP) (TMB)",
    "+Adler Armor (UUNP) (TMB)",
    "+TMB Vanilla Armors - 16.9.2016",
    "+Lind's Spellslinger Outfit (UUNP) (TMB)",
    "+Luxurious Seduction (UUNP) (TMB)",
    "-VS Ciri Project - UUNP HDT Bodyslide files + TMB meshes",
    "+Lind's Woodland Alchemist Dress (UUNP) (TMB)",
    "+Midnight Breed (UUNP) (TMB)",
    "+Fur Set (UUNP) (TMB)",
    "+PeroPero Armor (UUNP) (TMB)",
    "+West Wind Combat Series - Assault Armor (UUNP) (TMB)",
    "+Tribal Clothes [Demonica] (UUNP) (TMB)",
    "+PeroPero Vanilla Outfits Standalone (UUNP) (TMB)",
    "+Osare Culort Outfit (UUNP) (TMB)",
    "+Demon Hunter Armor (UUNP) (TMB)",
    "+DoA 5 – Christmas Set (TMB) [seasonal]",
    "+Nyotengu Christmas (TMB) [seasonal]",
    "+Nilfgaard Armor (TMB)",
    "+Bewitching Clothes (TMB) [seasonal]",
    "+Mearalikesmeads Sarongs (TMB)",
    "+Zzjay’s Wardrobe (TMB)",
    "-Ciri’s DLC Outfit (TMB)",
    "+Osare Underwear (TMB)",
    "+Sotteta Necromancer Outfit (TMB)",
    "+Gwelda Dawnguard Armor (TMB)",
    "+UNPCM Craftwear (TMB)",
    "+Keeping Warm - Scarves and Mufflers (TMB)",
    "+Wayfarer's Coat (TMB)",
    "+The Lily - Armour Mashup (TMB)",
    "+Swap Hide Armor (TMB)",
    "+Tembtra Thief Armor (TMB)",
    "+Scarlet Dawn Armor (TMB)",
    "+Skyrim Enhanced -High Polygons- UUNP - Alt Armor for Unique Races (TMB, UNPCM, CNHF)",
    "+Shocky's TERA Rogue Set + Tumblr Gift (UUNP) (TMB)",
    "+Shell Bondage (UUNP) (TMB)",
    "+ESO Altmer Armor by NewerMind43 RELOAD (UUNP) (TMB)",
    "+HotPants Bikini (UUNP) (TMB)",
    "+Ciri’s Outfit (TMB)",
    "-[x] Yennefer Armor UNPRT BETA",
    "+Northgirl Armor (TMB)",
    "+Crimson Twilight Armor (TMB)",
    "-[x] Fire Keeper Mask ＆ Cloak (UUNP)",
    "+The Book of UUNP",
    "+PeroPero MageRobes Standalone (UUNP)",
    "-TMB Vanilla Armors and Clothes V1 (Combined)",
    "-Vanilla Armors and Clothes – TMB (BETA)",
    "-Fox39TMBstandalone",
    "-Fox39 Lingeries (UNPRT)",
    "-Aether Suite House of Dibella [requires Aether Suite] (UNPRT)",
    "+[07c] ----------ARMOR & CLOTHING & ACCESSORIES - UUNP & UNPRT & UNPTF & TMB----------",
    "+Skyrim Enhanced -High Polygons- UUNP - Batch Build for Seraphim Body",
    "+[07b] ----------ARMOR & CLOTHING & ACCESSORIES - SERAPHIM----------",
    "+CN Accessories",
    "+UNP Armored Bikini",
    "+Amulets of Skyrim - USLEEP compatible",
    "+Bless 00022",
    "+UNPCM Craftwear Sadistic Magician (UUNP)",
    "+UNPCM Craftwear Rogue Couture Mashup (UUNP)",
    "-[x] Hunting Grounds (UUNP)",
    "+Skyrim Enhanced -High Polygons- (UUNP)",
    "+ESO Altmer Armor by NewerMind43 RELOAD (UUNP)",
    "+PeroPero Vanilla Outfit Replacer & Standalone (7B)",
    "+Nyotengu Christmas (7B) [seasonal]",
    "+PeroPero MageRobes Replacer - Standalone (7B)",
    "-Witcher 3 Ciri’s DLC Outfit (7B)",
    "+PeroPero Armor Pack (7B)",
    "+Rogue Sorceress Outfit (7B)",
    "+The Scout (7B)",
    "+Shocky's TERA Rogue Set + Tumblr Gift",
    "+Shell Bondage (7B)",
    "+Guild Wars 2 Lady Horus",
    "+Midnight Breed Armor - Modular with 5 Colors (7B)",
    "+Skyrim Necrosarium Set by Shocky",
    "+Mavari Armor (7B)",
    "+Lustmord Vampire Armour (7B)",
    "-Kalilies Ebony Catsuit (7B)",
    "+Ghorzas Armor (7B)",
    "+Hotpants Bikini (7BCH)",
    "+UNP Ranger Armor (UUNP) (TMB)",
    "+Mearalikesmeads Sarongs",
    "+West Wind Combat Series - Misfit Mage - Conversion UNPB UNP BBP BBPx TBBP",
    "+Kalilies Tumblr Gifts (UNPB)",
    "+Ashara Princess of the Woods (UNPB)",
    "+Swap Hide Armor - Craft Only (UNPB)",
    "+Unclaimed Delivery (UNPB)",
    "+Noldor Content Pack (UNPB)",
    "+Gilded Doublet (UNPB)",
    "+Crimson Twilight Armor (UNPB)",
    "+Imperial Investigator Armor by Calyps (UNPB)",
    "+Karter’s Herbalist Dress + Dark Luxury Mashup (UNP)",
    "-VS Ciri Project",
    "+Lind's Marksmage Garb (UUNP) (TMB)",
    "+Lind's Spellslinger Outfit",
    "+Lind's Woodland Alchemist Dress",
    "+Bewitching Clothes [seasonal]",
    "+SC - Witch of the Wilds",
    "+The Lily - Armour Mashup",
    "+DreamBurrows Patchwork Maiden Armor (UNP)",
    "+Brigida Dress Colour Variations",
    "+Osare Underwear (UNP)",
    "+Keeping Warm - Scarves and Mufflers",
    "+Ciri's Outfit (The Witcher) (UNP)",
    "+Kalilies Tumblr Gifts - Clothing & Accessories",
    "+Osare Culort Outfit (UNP)",
    "+Scarlet Dawn Armor (UNP)",
    "+UNP Viking Armors",
    "+zzjay's Wardrobe",
    "+Triss and Yennefer W3 Outfits HD Retexture [customized] (UNP)",
    "+Witcher 3 Female Armors",
    "+Nilfgaard Armor by zzjay",
    "+West Wind Combat Series - Misfit Mage (UNP)",
    "+West Wind Combat Series - Assault Armor UNP UNPB BBP",
    "+Tembtra Thief Armor (UNP)",
    "+Sotteta Necromancer Outfit (UNP)",
    "+Hunting Grounds Outfit",
    "+Luxurious Seduction Mashup",
    "+Lustmord Vampire Armor",
    "+Demon Hunter Armor by Jojjo",
    "+SKYDEVGRU Fine Imperial Dress Collection",
    "+VS Noble Archeress Dress Dovahkiin Edition",
    "+VS Medieval Archeress Dress",
    "+Northgirl Armor and the Retexture from clethcleth and Gamwich (UNP)",
    "+Ghorzas Armor (UNP)",
    "+ESO Altmer Armor by NewerMind43 RELOAD",
    "+Gwelda Dawnguard Armor (UNP)",
    "+Ashara Princes of the Woods (UNP) (Male)",
    "+Blades Hakama",
    "-[x] Fire Keeper Mask ＆Cloak",
    "+BDO Clead Cuirass Retouched",
    "+Bless Armors Pack by s666 Retouched",
    "+Linkle Outfit NINI Version",
    "+Bless MD0007",
    "+Ebony Valkyrie Armor",
    "+Omegared99 - Gallery of Armor",
    "+Apachii Divine Elegance Store",
    "+Adler",
    "+The Northern Overlord [seasonal]",
    "+FurArmorSet (FrostFall Aware)",
    "+Apophysis Dragon Priest Masks",
    "+Psychosteve's DragonPriest Masks",
    "+Ophelia Accessories",
    "+Grandmaster Ursine Armour",
    "+Mantle of the Silver Hand",
    "+Brigandage",
    "+Aetherial Crown",
    "+Skyrim Breastless Argonian Females",
    "+Sayka_Accessories",
    "+Wayfarer's Coat",
    "+TDN Equipable Horns",
    "+TDN Bosmer Skull Headdresses",
    "+Amulets of Skyrim",
    "+Feathers for Humanoid Males and Females",
    "+Chapel Shop",
    "+UNPCM Craftwear",
    "-Fluffy Travel Attire",
    "+Equipable Tongues",
    "+Deadly Trio",
    "+VS TW3 Anna Henrietta Riding Outfit",
    "+Snow White Crown (English)",
    "+Facial Piercings - Teldryn variant added",
    "+Facial Piercings",
    "+Flower Power",
    "+Noldor Content Pack",
    "+Dragon Age Mage Hawke Armor - Remodeled Version",
    "+Improved Closefaced Helmets",
    "+Leah Lilith Jewelry",
    "+KS Jewelry",
    "+Hedge Mage Armor",
    "+Harvest Feathers and Jasmine Flowers",
    "+Grace Darklings Ranger Armor V3",
    "+Grace Darklings Attire Packs",
    "+Wedding Rings by Ezuka",
    "+DreamBurrows Floral Head Accessory",
    "+Immersive Jewelry",
    "-Craftable Horse Barding",
    "+Calyps Barbarian Mashup (necklace only)",
    "+Warmonger Armory",
    "+Immersive Mashups Ver 2.0",
    "+Travel Robes",
    "+Contractor and Mavari Armors",
    "+Common Clothes",
    "+Wearable Lanterns",
    "+DreamBurrows Regal Assassin Armor",
    "+DreamBurrows Regal Huntsman Armor",
    "+Armor Of Intrigue",
    "+SC - Halamshiral Ballgown",
    "+Nerevars - Cloaks of Skyrim Ultra HD",
    "+Angelika Amulets",
    "+Winter Is Coming - Cloaks (assets only)",
    "+Cloaks of Skyrim (assets only)",
    "+Bandolier - Dawnguard (assets only)",
    "+Bandolier - Bags and Pouches (assets only)",
    "+EotW Dovahkiins Journeyman Armor",
    "+Battlemage Armour (Female)",
    "-Hedge Mage Armor (7B)",
    "-SOS-Enabled StraponDoubleDildo Replacer for SexLab",
    "-Rayban-like Sunglasses",
    "+[07a] ----------ARMOR & CLOTHING & ACCESSORIES - VANILLA & OTHER BODIES----------",
    "+[07] ----------ARMOR & CLOTHING & ACCESSORIES----------",
    "-TEMPORARY _ Brawl Bugs - Compatibility Edition",
    "+Body Hair Face - Merged",
    "+Body Hair Face - Patch",
    "+RaceMenu - Merged",
    "+SOS - Merged",
    "+[06h] ----------BODY & HAIR & FACE - MERGED----------",
    "+My RaceMenu Presets",
    "+[06g] ----------BODY & HAIR & FACE - PRESETS----------",
    "+Salt and Wind - Rough Hair for KS Hairdos",
    "-Fair Skin Complexion 9.2 - CustomBreton, tintmasks, detail masks, mouth",
    "+All-in-One HDT Animated Pussy - HDT files only",
    "-gwynhyrs-saga female textures (uncompressed 4k)",
    "+KS Hairdos - Renewal Breast Weight Painted Hair",
    "+thePure (for elves)",
    "+Green eye retex for New Mikan Eyes (nme_F_2S_003)",
    "+Nezzar’s HD Dirt and Scars",
    "+XCE - Warpaint and Dirt",
    "+Maevan2's Eye Brows",
    "+Odontaphobia",
    "+Smashin Face Overhaul",
    "+Improved Eye Reflections and Cube Map",
    "+Eyebrow Specularity Fix",
    "+DreamBurrows Lion Eyes",
    "+BVFE - Better Vampire Fangs and Eyes",
    "+Better Vanilla Hairs - Mesh Replacements",
    "-SOS - Equipable Schlong - SG Renewal patch",
    "+ApachiiSkyHair Natural Retexture - Full + male + female",
    "+[06f] ----------BODY & HAIR & FACE - OTHER MESHES & TEXTURES----------",
    "+Demoniac_Texture (for CustomBreton)",
    "+TMB CustomBreton Body",
    "-CustomBreton - SRG Female Textures (diffuse and normal)",
    "-CustomBreton - Mega Milkdrinker textures + Better Makeup for SKSE",
    "+[06e] ----------BODY & HAIR & FACE - CUSTOM RACES----------",
    "+Fair Skin Complexion - Freckles only",
    "+HN66s Long Eye Lashes",
    "-Full HDT Physics Kit",
    "+Demoniac_Texture",
    "+Better Makeup for SKSE",
    "-UUNP Special + Mature Skin Textures + Real Girls patch",
    "-Real Girls Realistic Body Texture for UNP UNPB and SeveNBase",
    "+Feminine Khajiit Textures for CBBE-UNP (Grey Cat and Leopard)",
    "+Feminine Argonian Textures for CBBE-UNP (Chameleon and Lizard)",
    "+UUNP Special Seraphim (Default)",
    "+[06d] ----------BODY & HAIR & FACE - FEMALE----------",
    "+The Veteran Skin - Less saturated lips",
    "+The Veteran Skin - MFMiraakRace patch",
    "-MFMiraakRace SkySight Skins - Ultra HD Male Textures and Real Feet Meshes (4K2K HIGH)",
    "-CustomBreton SkySight Skins - Ultra HD Male Textures and Real Feet Meshes (4K2K HIGH)",
    "+The Veteran Skin - 4K Nude Male Skin with SoS Support",
    "-Eiries' Skysight SoS Patch",
    "-SkySight Skins - Ultra HD Male Textures and Real Feet Meshes (4K2K HIGH)",
    "+SOS assets - Collision Data added",
    "+Masculine Argonian Textures for SOS (Chameleon and Lizard)",
    "+Masculine Khajiit Textures for SOS (Grey Cat and Leopard)",
    "-Fine Face Textures for Men by Urshi - Black Subsurface Maps for Male Face and Body",
    "-DCE - Realistic Male Face (Smooth)",
    "-Smooth Male Body - Textures for Better Males - SOS Schlongs of Skyrim",
    "-SOS - Custom Body Textures for Schlongs of Skyrim",
    "+SOS - RaceMenu Plugin",
    "-FemFeet Redesigned",
    "+SOS - Protective Undies for Schlongs of Skyrim",
    "+SOS - Schlongs of Skyrim",
    "+[06c] ----------BODY & HAIR & FACE - MALE----------",
    "+Pubic Hairstyle Overlays for RaceMenu UNP CBBE",
    "+SOS - Equipable Schlong - no balls",
    "+Kai's Makeup for Skyrim",
    "+TairenSoul Warpaints Collected",
    "+Raven's Warpaint",
    "+Battle Hardened Warpaints",
    "+Lind's Human Eyes",
    "+Lind's Elven Eyes",
    "+LiEyes - Eye pack SA",
    "+Precious Style Eyes (Reflexion Version)",
    "+New Mikan Eyes for Custom Races",
    "+New Mikan Eyes",
    "+Mikan Eyes",
    "+Hale - Iridum Eyes",
    "-Eyes of Aber",
    "+Nana's Bshittery Eye Pack",
    "-Eyes for Everyone Except Beast Races",
    "+ENSE HD + Heterochromia",
    "+The Eyes Of Beauty",
    "+Body Scars for RaceMenu",
    "+Freckle Mania",
    "+Northborn Scars",
    "+SG Female Eyebrows",
    "+Brows",
    "+Beards",
    "+KS Hairdos - HDT Physics",
    "+KS Hairdos Renewal",
    "+SC - Hairstyles",
    "+Kalilies Tumblr Gifts - Hair",
    "+KS Cazy Hairs",
    "+Kalilies Tumblr Exclusive Hair Pack (follower gift)",
    "-NUHairstyles",
    "+Lovely Hairstyles",
    "+SG Hair Pack 268 Edition",
    "+ApachiiSkyHair - Full + male + female",
    "+[06b] ----------BODY & HAIR & FACE - NEW PARTS----------",
    "+Simple Retexture for Afflicted",
    "+XP32 Maximum Skeleton Extended - XPMSE",
    "+TMB – Tiddy McButt Body - BodySlide Files",
    "+UNPTF BodySlide Presets",
    "+BodySlide and Outfit Studio",
    "+RaceMenu Overlays Plugin",
    "+RaceMenu",
    "+Final Younger Characters",
    "+Eyes Glitch Fix",
    "+[06a] ----------BODY & HAIR & FACE - GENERAL----------",
    "+[06] ----------BODY & HAIR & FACE----------",
    "+Subtle Cloak Spell Graphics",
    "+Holy Wards - A Retexture",
    "+[05d] ----------TEXTURES & MESHES - MAGIC----------",
    "+JS Dragon Claws",
    "+Snazzy HD Furniture and Clutter",
    "+HD Quill of Gemination",
    "+Snazzy HD Noble Beds",
    "+A lute from Witcher 3",
    "+ImprovedGlowingGlowdust",
    "+Potion Replacer",
    "+Book Covers Skyrim - Merged",
    "+Book Covers Skyrim - USLEEP Patch",
    "+Book Covers Skyrim - Lost Library",
    "+Book Covers Skyrim",
    "-Trade Tents from Hiro Solitude",
    "-Skyrim Realistic Texture Overhaul Dwemer - Dwemer 2K",
    "+RUSTIC ALCHEMY and ENCHANTING TABLES",
    "+PELTAPALOOZA - Pelts of Skyrim Expansion",
    "+Nazenn's Dragon Bridge mesh",
    "-Joy of Ships",
    "-Embers HD - Forges Add-On",
    "+Enhanced Blood Textures",
    "+[05c] ----------TEXTURES & MESHES - ITEMS AND OBJECTS----------",
    "+EotW Dawnguard DLC Textures Remastered",
    "+[05b] ----------TEXTURES & MESHES - OVERHAUL----------",
    "+SMC - Merged",
    "+SMC - Smashed Patch",
    "+SMC",
    "+[05a] ----------TEXTURES & MESHES - SMC----------",
    "+[05] ----------TEXTURES & MESHES----------",
    "+Unlimited Bookshelves",
    "+[04] ----------BUG FIXES PART 1----------",
    "+Interfaces - Merged",
    "+Sky Complete - Merged",
    "+[03b] ----------USER INTERFACES - MERGED----------",
    "+SkyComplete (inc. Wyrmstooth and Falskaar)",
    "+moreHUD",
    "+Simple Crosshair",
    "+No Menu and Loading Smoke",
    "-MainMenu",
    "-Custom Main Menu Wallpaper",
    "+Main Menu Wallpaper Replacer HD 1080p",
    "+Main Font Replacement - Fertigo",
    "+iWASM - Immersive Wait And Sleep Menu",
    "+Immersive HUD - iHUD",
    "+Customizable Camera",
    "+A Quality World Map and Solstheim Map - With Roads",
    "+A Matter of Time - A HUD clock widget",
    "-Quick Loot",
    "+Atlas Map Markers - Updated with MCM",
    "+[03a] ----------USER INTERFACES - GENERAL----------",
    "+[03] ----------USER INTERFACES----------",
    "+Clothing and Clutter Fixes",
    "+Weapons and Armor Fixes Remade",
    "+Complete Crafting Overhaul Remade",
    "+Skyrim -Community- Uncapper",
    "+Skyrim - Enhanced Camera",
    "+SkyRealism - Time and Travel",
    "+Realistic Ragdolls and Force",
    "+Random Vampire Attacks in Towns Disabled",
    "+Cutting Room Floor",
    "-SexLab Framework",
    "+[02] ----------LOAD EARLY----------",
    "+Utilities - Merged",
    "+Utilities Merged - Manual Patch",
    "+[01c] ----------UTILITIES - MERGED----------",
    "+Better Console",
    "+JContainers",
    "+OSA - Skyrim Ascendancy Engine",
    "+Killcam blur removal",
    "+Better Jumping",
    "+No more junk",
    "+Crash fixes",
    "+SkyTweak",
    "+Grimy Utilities",
    "+SkyUI",
    "+Jaxonz Diagnostics",
    "+Jaxonz MCM Kicker",
    "+Cobb Positioner",
    "+AddItemMenu - Ultimate Mod Explorer",
    "+Sometimes Pick Up Books",
    "+No Poison Dialogues",
    "+No Enchantment Restrictions - SKSE No Conflict",
    "+UIExtensions",
    "+Clean Up",
    "+Smart Cast",
    "+Sleep Menu Extender",
    "+Custom Races (Redux)",
    "+Fuz Ro Doh",
    "+Antique Dragon ENB - Face Light Darker",
    "+Puppeteer Master",
    "+Blocksteal Redux",
    "+Auto Unequip Ammo",
    "+Auto Killcam Screenshot",
    "+[01b] ----------UTILITIES - OTHER----------",
    "+DienesTools",
    "+Fores New Idles in Skyrim - FNIS",
    "+HDT HighHeels System",
    "+HDT Physics Extensions",
    "+General Displays",
    "+Grimy Plugin",
    "+RaceCompatibility for Skyrim and Dawnguard",
    "+FileAccess Interface for Skyrim Script - FISS",
    "+PapyrusUtil - Scripting Utility Functions",
    "+OneTweak",
    "+Mfg Console",
    "-Safety Load",
    "+Memory Blocks Log",
    "+SKSE INI tweaks",
    "+SKSE 1.7.3 scripts",
    "+[01a] ----------UTILITIES - CORE----------",
    "+[01] ----------UTILITIES----------",
    "+TES5Edit Modgroups & Backups",
    "+Speed and Stability Guide for ENB - Subsurface Scattering Patch",
    "+Unofficial Skyrim Legendary Edition Patch",
    "+Unofficial High Resolution Patch",
    "-[!] Unofficial Dragonborn Patch",
    "+Optimized Dragonborn Textures - HD",
    "+Dragonborn.esm - Cleaned",
    "-[!] Unofficial Hearthfire Patch",
    "+Optimized HearthFires Textures - HD",
    "+Hearthfires.esm - Cleaned",
    "-[!] Unofficial Dawnguard Patch",
    "+Optimized Dawnguard Textures - HD",
    "+Dawnguard.esm - Cleaned",
    "-[!] Unofficial Skyrim Patch",
    "+Optimized Vanilla Textures - HD",
    "*Unmanaged: HighResTexturePack03",
    "*Unmanaged: HighResTexturePack02",
    "*Unmanaged: HighResTexturePack01",
    "+Update.esm - Cleaned",
    "+[##] ----------DLC & BASE PATCHES----------",
    "*Unmanaged: Dawnguard",
    "*Unmanaged: Dragonborn",
    "*Unmanaged: HearthFires"
]